version: '3.8'

services:
  db:
    image: postgres:15
    container_name: smarttrade-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: smarttrade
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:7
    container_name: smarttrade-redis
    ports:
      - "6380:6379"
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: smarttrade-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@smarttrade.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5051:80"
    depends_on:
      - db
    restart: always

volumes:
  postgres_data:
